### ISSUE TITLE
 IE compatibility in Adapt V4

### ISSUE THREAD

**Issue by michiem** [cgkineo/adapt-documentMode#2]
Since Adapt v4 is not working in compatibility view, can we put some pop up or alert for the learner for them to know thay the course will not work in compatibility view?

Also, I tried to use the adapt-IE-check plugin and it is not working when in compatibility view.

**Comment by moloko** [comment]
@michiem please could you provide more detail than 'it is not working'?

**Comment by moloko** [comment]
It's not this extension that's failing, it's the use of `document.addEventListener` within the version of scriptLoader.js that's used in Adapt v3 and later that's triggering a script error in IE11 if running in IE7 or IE8 mode, halting further JavaScript execution.

Works fine with Adapt v2 (which is the version this extension was originally built for); also later versions where document mode >= 9
